### ISSUE TITLE
questions about TSN features

### ISSUE THREAD

**Issue by meryusha** [epic-kitchens/C2-Action-Detection#3]
Hi, thank you once more for providing an easy-to-use code!
Could you please clarify some details about the work? 
I have some questions regarding the rescaled TSN features. You mentioned in the paper that 400 is a large window but did you try to use a larger one, and (if yes) how did it affect the performance?
Also, there are not many details about the features themselves. As far as I understand, the features extractor is TSN with a BN-Inception backbone? 
Thank you

**Comment by antoninofurnari** [comment]
Hello,

Thank you for your interest in our dataset and challenges! 

400 is the largest window we tried due to computational constraints. In our settings (as you can test by using this code), training of BMN required 4 V100 with 16GB ram each. In the initial exploratory experiments, we did try to break videos into smaller chunks so that the same window of 400 would capture a finer temporal resolution, but that seemed not to improve performance.

Regarding the features, yes, that's correct, we extracted features using a TSN model with BNInception backbone trained for action recognition using 3 temporal segments. Please note that the features are the same as the ones used for action anticipation (see https://github.com/epic-kitchens/C3-Action-Anticipation/ and https://github.com/fpv-iplab/rulstm).

Please let me know if you have any other question.

Best,
Antonino
